/*
 * Unicorn Rest Interface
 *
 * This is to provide rest interface to Unicorn. The rest API's can be used to execute and manage the tests. 
 *
 * API version: 1.0.0
 * Contact: rakeshkumbi@telaverge.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
)

func UnicornOperationHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
