/*
 * Unicorn Rest Interface
 *
 * This is to provide rest interface to Unicorn. The rest API's can be used to execute and manage the tests. 
 *
 * API version: 1.0.0
 * Contact: rakeshkumbi@telaverge.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger_server

import (
	"net/http"
	wrapper "unicorn/swagger/swagger_wrapper"
)

func UnicornOperationHandler(w http.ResponseWriter, r *http.Request) {
	wrapper.WrapperUnicornOperationHandler(w, r)
}
