/*
 * Unicorn Rest Interface
 *
 * This is to provide rest interface to Unicorn. The rest API's can be used to execute and manage the tests. 
 *
 * API version: 1.0.0
 * Contact: rakeshkumbi@telaverge.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger_server

import (
	"net/http"
	wrapper "unicorn/swagger/swagger_wrapper"
)

func ListSUTs(w http.ResponseWriter, r *http.Request) {
	wrapper.WrapperListSUTs(w, r)
}

func ListTestCases(w http.ResponseWriter, r *http.Request) {
	wrapper.WrapperListTestCases(w, r)
}

func ListTestSuites(w http.ResponseWriter, r *http.Request) {
	wrapper.WrapperListTestSuites(w, r)
}

func StatsHandler(w http.ResponseWriter, r *http.Request) {
	wrapper.WrapperStatsHandler(w, r)
}

func SutExecutionHandler(w http.ResponseWriter, r *http.Request) {
	wrapper.WrapperSutExecutionHandler(w, r)
}

func TestcaseExecutionHandler(w http.ResponseWriter, r *http.Request) {
	wrapper.WrapperTestcaseExecutionHandler(w, r)
}

func TestsuiteExecutionHandler(w http.ResponseWriter, r *http.Request) {
	wrapper.WrapperTestsuiteExecutionHandler(w, r)
}
