/*
 * Unicorn Rest Interface
 *
 * This is to provide rest interface to Unicorn. The rest API's can be used to execute and manage the tests. 
 *
 * API version: 1.0.0
 * Contact: rakeshkumbi@telaverge.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger_server

type TestCaseStatistics struct {

	TestStatus string `json:"testStatus,omitempty"`

	TestDuration string `json:"testDuration,omitempty"`

	TimeElapsed string `json:"timeElapsed,omitempty"`

	Stats string `json:"stats,omitempty"`
}
