/*
 * Unicorn Rest Interface
 *
 * This is to provide rest interface to Unicorn. The rest API's can be used to execute and manage the tests. 
 *
 * API version: 1.0.0
 * Contact: rakeshkumbi@telaverge.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/telaverge41/indresh/1.0.0/",
		Index,
	},

	Route{
		"ListSUTs",
		strings.ToUpper("Get"),
		"/telaverge41/indresh/1.0.0/tests/{operation}",
		ListSUTs,
	},

	Route{
		"ListTestCases",
		strings.ToUpper("Get"),
		"/telaverge41/indresh/1.0.0/tests/{sut}/{testsuite}/{operation}",
		ListTestCases,
	},

	Route{
		"ListTestSuites",
		strings.ToUpper("Get"),
		"/telaverge41/indresh/1.0.0/tests/{sut}/{operation}",
		ListTestSuites,
	},

	Route{
		"StatsHandler",
		strings.ToUpper("Get"),
		"/telaverge41/indresh/1.0.0/tests/{sut}/{testsuite}/{testcase}/{operation}",
		StatsHandler,
	},

	Route{
		"SutExecutionHandler",
		strings.ToUpper("Post"),
		"/telaverge41/indresh/1.0.0/tests/{sut}/{operation}",
		SutExecutionHandler,
	},

	Route{
		"TestcaseExecutionHandler",
		strings.ToUpper("Post"),
		"/telaverge41/indresh/1.0.0/tests/{sut}/{testsuite}/{testcase}/{operation}",
		TestcaseExecutionHandler,
	},

	Route{
		"TestsuiteExecutionHandler",
		strings.ToUpper("Post"),
		"/telaverge41/indresh/1.0.0/tests/{sut}/{testsuite}/{operation}",
		TestsuiteExecutionHandler,
	},

	Route{
		"UnicornOperationHandler",
		strings.ToUpper("Get"),
		"/telaverge41/indresh/1.0.0/unicorn/{operation}",
		UnicornOperationHandler,
	},
}
